# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kamoya-pswd
      POSTGRES_USER: kamoya-user
      POSTGRES_DB: kamoya-dbs
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080