
services:
 mysql:
  image: "mysql:8.0"
  restart: always
  ports:
  #HOST_PORT : CONTAINER_PORT
   - 3307:3306
  environment:
   MYSQL_DATABASE: "db_name"
   ###for None root user user_name  : uncomment the line below
   # MYSQL_USER: "erp_user"
   ### for None root user user_password : uncomment the line below
   # MYSQL_PASSWORD: "erp_password"
   MYSQL_ROOT_PASSWORD: "root_password"
  volumes:
   - my-vol:/var/lib/mysql

volumes:
 my-vol: