
services:
 mysql:
  image: "mysql:8.0"
  restart: always
  ports:
  #HOST_PORT : CONTAINER_PORT
   - 3307:3306
  environment:
   ##for None root user user_name  : uncomment the line below
   # MYSQL_USER: "YOUR_USER_NAME"
   ### for None root user user_password : uncomment the line below
   # MYSQL_PASSWORD: "YOUR_PASSWORD"
   # MYSQL_ROOT_PASSWORD: "root_password"
   # MYSQL_DATABASE: "DATABASE_NAME"
   MYSQL_ALLOW_EMPTY_PASSWORD: yes
  volumes:
   - my-vol:/var/lib/mysql

volumes:
 my-vol: